Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Colors.xcassets/Contents.json
Journey/Journey/Resources/Colors.xcassets/White.colorset/Contents.json
Journey/Journey/Sources/Extensions/Example+Extension.swift
Journey/Journey/Sources/Extensions/UIColor+Extension.swift

[#3] 컬러 에셋 만들기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Sources/Extensions/UINavigationController+Extension.swift

- 네비게이션 바 숨기는 함수 작성
- back button이 없는 네비바 init 함수 작성
- back button이 있는 네비바 init 함수 작성
Resolve #5

[#5] Navigation Controller Extension

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Colors.xcassets/CourseBgGray.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/CourseUndoneGray.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Pink.colorset/Contents.json
Journey/Journey/Resources/Constants/Xib.swift
Journey/Journey/Sources/Cells/CellExmaple.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Journey/Journey/Sources/Extensions/UIView+Extension.swift

- 1일차 cell
- 짝수일차 cell
- 홀수일차 cell
- UIView Rounding Extension
- UIColor Update
Resolve #11

[#11] Course Table View Cell 만들기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
Journey/Journey/Sources/APIModels/Challenge.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- @IBOutlet Properties 연결
- view rounding 처리
- tableview - delegate, datasource 연결
- 짝,홀수 로직
- 진행 일수에 따라 road 색깔 처리
https://user-images.githubusercontent.com/28949235/123925819-3cb24480-d9c6-11eb-9b5b-b98b54d55061.mov
Resolve #12

[#12] Course 뷰 로직

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Colors.xcassets/doneCourseBg.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/doneCourseButton.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/undoneCourseBg.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/undoneCourseButton.colorset/Contents.json
Journey/Journey/Resources/Constants/Storyboard.swift
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Resources/Constants/Xib.swift
Journey/Journey/Resources/Storyboards/Challenge/CourseLibrary.storyboard
Journey/Journey/Sources/AppModels/Course.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift

- 뷰 설계
- SB, VC 만들기
- cell 만들기
- 연결
- 로직 처리
https://user-images.githubusercontent.com/28949235/123945610-4f824480-d9d9-11eb-95bb-e3d861d3e7aa.mov
Resolve #18

[#18] 코스 라이브러리 뷰

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/Storyboard.swift
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Sources/SceneDelegate.swift
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

- 로그인 storyboard
- flow 연결
Resolve #20

[#20] 로그인 flow

---

Journey/Journey.xcodeproj/project.pbxproj

[#NON_ISSUE] 파일 경로 수정

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/URL.swift

[#37] URL Constant 추가하기 

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Journey/Journey/Sources/ViewModels/CourseListViewModel.swift

- migration
- CourseListViewModel 생성
Resolve #24

[#24] CourseLibrary 뷰 MVVM 패턴으로 migration하기

---

Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- Size Enum 만들기
- Point 다듬기
- NextPath 분리하기
- nextSituation에 따라 색 분기처리
Resolve #15

[#15] Course cell들 CGPoint 다듬기

---

README.md

- 쟈니 간단한 설명 추가
- 팀원 추가
Resolve #38

[#38] README 수정

---

Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- Course
- Challenge
Resolve #48

[#48] Model에 맞게 더미데이터 수정

---

Journey/Journey/Resources/Storyboards/Home/Home.storyboard
Journey/Journey/Resources/Storyboards/Home/Medal.storyboard
Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift

[#48] Medal 뷰 트랜지션 연결

---

Journey/Journey/Resources/Storyboards/Home/Home.storyboard
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- courseTableView footer 추가
Resolve #16

[#16] courseTableView footer

---

Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

- UIimage 생성
- 이메일 / 비밀번호 텍스트필드 생성
- 로그인 버튼 생성
- 비밀번호 찾기 회원가입 생성
Resolve #53

[#53] 로그인뷰 짜기

---

Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift

- 로그인 nav init function
- 회원가입 1 nav init function
- @IBOutlet Function 이름 변경
Resolve #66

[#66] 로그인, 회원가입 flow navigation bar init functions

---

Journey/Journey/Resources/Constants/URL.swift

- Moya 사용을 고려한 URL Constant 추가
- 아직 안 나온 api (PW찾기, 소확행 삭제, 푸시알림)은 추가하지 않음
Resolve #41

[#41] URL Constant 정리하기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/URL.swift
Journey/Journey/Resources/Info.plist
Journey/Journey/Sources/APIServices/NetworkResult.swift

- info.plist - Allow Arbitary Loads
- NetworkResult
Resolve #62

[#62] 서버 통신 전 환경설정

---

Journey/Journey/Resources/Storyboards/Feed/Mood.storyboard
Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift

[#71] 기분선택 - 글작성 트랜지션 연결

---

Journey/Journey/Resources/Storyboards/Feed/Writing.storyboard
Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.swift
Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.xib
Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift

- 해시태그 최대 개수 제한 -> 팝업
- 해시태그 X 버튼 클릭 시 삭제
Resolve #82

[#82] 해시태그 로직 추가

---

Journey/Journey/Resources/Colors.xcassets/Black1.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Black1Text.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Black2.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Black2Text.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Black3Text.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Green.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey1Bg.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey1Line.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey1Tab.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey2Bg.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey2Line.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Grey2Tab.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/GreyBtnInactive.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Icon.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Pink2.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Pink3.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/PinkMood.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/Red.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/black4Text.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/pink1.colorset/Contents.json
Journey/Journey/Sources/Extensions/UIColor+Extension.swift

- Color System 정리
- Color Set 추가
- UIColor Extension에 추가
Resolve #79

[#79] Color System 정리

---

Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib

커스텀 팝업 띄울 때 탭바가 위로 올라오는 현상 해결
Resolve #87

[#87] 커스텀 팝업 띄울 때 탭바가 위로 올라오는 현상 해결

---

Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib

- PopUpActionDelegate 추가
- WritingViewController에서 PopUpActionDelegate 채택
```var hashTagPopUp: PopUpViewController = PopUpViewController()```
```
hashTagPopUp = PopUpViewController(nibName: "PopUpViewController", bundle: nil)
hashTagPopUp.modalPresentationStyle = .overCurrentContext
hashTagPopUp.modalTransitionStyle = .crossDissolve
hashTagPopUp.popUpUsage = .noTitle
hashTagPopUp.popUpActionDelegate = self
tabBarController?.present(hashTagPopUp, animated: true, completion: nil)
hashTagPopUp.pinkButton?.setTitle("확인", for: .normal)
hashTagPopUp.descriptionLabel?.text = "태그는 최대 5개까지\n 입력할 수 있어요!"
```
```
extension WritingViewController: PopUpActionDelegate {
func touchPinkButton(button: UIButton) {
self.hashTagPopUp.dismiss(animated: true, completion: nil)
}
func touchWhiteButton(button: …
```

[#90] Pop Up view Action delegate

---

Journey/Journey/Sources/AppDelegate.swift

- enableAutoToolbar
- shouldResignOnTouchOutside
Resolve #91

[#91] IQKeyboardManager 옵션 추가

---

Journey/Journey/Sources/APIModels/Challenge.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- title
- Model 수정
- VC 수정
Resolve #76

[#76] Course 뷰 서버 수정사항 반영

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/Storyboard.swift
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
Journey/Journey/Sources/ViewControllers/Auth/FindPasswordViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

[#96] 비밀번호 찾기 뷰 짜기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/Storyboard.swift
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
Journey/Journey/Sources/ViewControllers/Auth/CodeViewController.swift

[#98] 인증코드 뷰 짜기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/Storyboard.swift
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
Journey/Journey/Sources/ViewControllers/Auth/NewPasswordViewController.swift

[#100] 새 비밀번호 뷰 짜기

---

Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib

- 오늘, 아직 미완인 챌린지에도 BgCircle의 색은 Pink
- Cell에 Color System 적용
Resolve #77

[#77] Course 뷰 수정사항 반영

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Constants/ViewController.swift
Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
Journey/Journey/Sources/SceneDelegate.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift

[#NON_ISSUE] conflict 해결

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Journey/Journey/Sources/Extensions/UIDevice+Extension.swift
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift

- Component 배치
- 노치에 유무에 따른 스탬프 오토레이아웃
Resolve #29

[#29] 챌린지뷰 짜기

---

Journey/Journey/Resources/Storyboards/Auth/Login.storyboard

[#127] 로그인뷰 오토레이아웃 수정

---

Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

- 시작하기 버튼 오토레이아웃 수정
- 서비스 텍스트 밑줄, 폰트 넣기
Resolve #128

[#128]  SignUpThird 뷰 수정

---

Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard

- 시작하기 버튼 오토레이아웃 수정
- 텍스트필드 오토레이아웃 수정
- 이메일, 패스워드 라벨 수정
Resolve #131

[#131] SignUpFirst 오토레이아웃 수정

---

Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard

-  계속하기 버튼 오토레이아웃 수정
Resolve #133

[#133] SignUpSecond 오토레이아웃 수정

---

Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

- signUpFirst
- signUpSecond
- signUpThird
-  login 좌우
-  닉네임 에러 label 처음에 hidden
Resolve #140

[#140] 회원가입 뷰들 상단, 좌우 constraint 변경

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Sources/APIServices/AuthAPI/LoginAPI.swift
Journey/Journey/Sources/APIServices/AuthAPI/LoginService.swift
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

- 서비스 만들기
- 통신 함수 만들기
- 뷰컨에서 사용하기
Resolve #144

[#144] 로그인뷰 서버연결

---

Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift

[#104] 현재 진행중인 코스 몇일차인지 탐색

---

Journey/Journey/Sources/APIServices/AuthAPI/SignUpAPI.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

-  print 뺄게요 ㅋㅋ ㅈㅅㅎㄴㄷ
Resolve #169

[#169] 회원가입 뷰 코드 수정

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Sources/APIServices/AuthAPI/LoginService.swift
Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeService.swift
Journey/Journey/Sources/APIServices/CourseAPI/CourseService.swift
Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
Journey/Journey/Sources/APIServices/HomeAPI/HomeService.swift
Journey/Journey/Sources/AppDelegate.swift
Journey/Journey/Sources/SceneDelegate.swift
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

[#170] UserDefaults에 jwt, fcm token 저장하기

---

Journey/Journey.xcodeproj/project.pbxproj
Journey/Journey/Sources/APIModels/Challenge.swift
Journey/Journey/Sources/APIModels/Community.swift
Journey/Journey/Sources/APIModels/Course.swift
Journey/Journey/Sources/APIModels/Feed.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift

- 모델 변경사항 반영
- 더미데이터 수정
Resolve #185

[#185] 모델 변경사항 반영

---

Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeAPI.swift
Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeService.swift
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift

- Service 만들기
- API 만들기
- 챌린지 뷰컨에 연결
Resolve #173

[#173] 챌린지뷰 서버통신

---

Journey/Journey/Resources/Constants/Xib.swift
Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
Journey/Journey/Sources/APIServices/CourseAPI/CourseService.swift
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift

[#158] 코스 라이브러리에서 코스 시작/변경 통신 연결

---

Journey/Journey/Sources/APIModels/Home.swift
Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift

[#176] home 데이터 course 속성 optional 처리

---

Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Journey/Journey/Resources/Storyboards/Challenge/EmptyChallenge.storyboard
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift

- @IBOutlet  연결
- empty 뷰 띄우기
Resolve #201

[#201] 챌린지 뷰 코스 여부 분기

---

Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Journey/Journey/Sources/Views/FeedHeaderView.swift
Journey/Journey/Sources/Views/FeedHeaderView.xib

- 0, 1, 2, 3에 따라 버튼 팝업 분기
Resolve #152

[#152] 소확행 작성 버튼 분기 팝업

---

Journey/Journey/Resources/Info.plist
Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard

- login view layout bug fix
Resolve #223

[#223] login view layout bug fix

---

Journey/Journey/Resources/Storyboards/Home/Home.storyboard
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift

- 메인 뷰 문구 수정
- 속성 아이콘 변경
Resolve #226

[#226] main 뷰 문구, 속성 아이콘 수정

---

Journey/Journey/Resources/Assets.xcassets/btnSide.imageset/Contents.json
Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/Contents.json
Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
Journey/Journey/Resources/Storyboards/Challenge/CourseLibrary.storyboard
Journey/Journey/Resources/Storyboards/Home/Home.storyboard
Journey/Journey/Resources/Storyboards/Home/Medal.storyboard
Journey/Journey/Resources/Storyboards/Home/Setting.storyboard
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.xib
Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.xib
Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.xib
Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Journey/Journey/Sources/Views/DatePickerViewController.xib
Journey/Journey/Sources/Views/FeedHeaderView.xib
Journey/Journey/Sources/Views/MedalCollectionReusableView.xib
Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib
Journey/Journey/Sources/Views/YearPickerViewController.xib

[#145] 다크모드 점검

---

Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

[#210] SignUpThird 뷰 정규식 넣기

---

Journey/Journey/Resources/Constants/Image.swift
Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift

- DoneCourse cell property에 따라 속성 추가하기
- 코스 변경/시작 로직
Resolve #218

[#218] DoneCourse cell property, 코스 변경 로직

---

Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Journey/Journey/Sources/Views/YearPickerViewController.xib

[NON_ISSUE] compileXib error 해결

---

Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift

- course 뷰 프로퍼티로 아이콘 분기처리
Resolve #230

[#230] course 뷰 프로퍼티로 아이콘 분기처리

---

Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift

[#237] SignUpFirst 수정

---

Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift

- 챌린지 뷰 초기에 label에 따라 bgView frame 수정이 안 되는 문제
Resolve #217

[#217] 챌린지 뷰 초기에 label에 따라 bgView frame 수정이 안 되는 문제

---

Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift

- 회원가입 뷰 네비게이션 바 init 함수 추가
Resolve #216

[#216] 회원가입 뷰 네비게이션 바 init 함수 추가

---

Journey/Journey/Resources/Info.plist
Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.swift
Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Journey/Journey/Sources/Views/YearPickerViewController.xib

-  다크모드 아예 못하게
- signup view color 수정
- year picker view 버튼 중앙정렬
- 로직 수정
Resolve #245

[#245] 전체 오토레이아웃, 다크모드 점검

---

Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

-  글씨색 바꾸기
-  패스워드 라벨 보이기
Resolve #248

[#248] 글씨색 바꾸기, 패스워드 라벨 보이기

---

Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift

- 해시태그 4개 넘어 갈때 인덱스 에러 수정
Resolve #251

[#251] 해시태그 인덱스 에러 수정

---

Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift

- nil 에서 빈 스트링으로 변경
Resolve #254

[#254] default 이미지 조건 값 수정

---

Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift

- viewWillApper로 서버 통신 이동
Resolve #256

[#256] homeView life cycle 수정

---

Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift

- userMent index error
Resolve #262

[#262] userMent index error

---

Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift

- Login indicator 추가
Resolve #146

[#146] activity indicator 추가

---

Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift

- Activity Indicator 붙이기
Resolve #146

[#146] Activity Indicator 붙이기

---

Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift

- 피드, 내 서랍장 로딩 인디케이터 추가
Resolve #146

[#146] 로딩 인디케이터 추가

---

Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift

- EmptyCourse 뷰 앞으로 보내기
Resolve #267

[#267] EmptyCourse 뷰 앞으로 보내기

---

Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift

- 내 서랍장 조회 안되는 버그 해결
Resolve #269

[#269] 내 서랍장 날짜 버그 수정

---

Journey/Journey/Resources/Constants/URL.swift

[#281] base url 변경

---

Journey/Journey/Sources/APIModels/Auth.swift
Journey/Journey/Sources/APIModels/Course.swift
Journey/Journey/Sources/APIModels/Medal.swift
Journey/Journey/Sources/APIServices/AuthAPI/LoginAPI.swift
Journey/Journey/Sources/APIServices/AuthAPI/PasswordAPI.swift
Journey/Journey/Sources/APIServices/AuthAPI/SignUpAPI.swift
Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeAPI.swift
Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
Journey/Journey/Sources/Extensions/UIColor+Extension.swift

-  GenericResponse
-  api 함수부분 수정
- AuthAPI
- CourseAPI
- ChallengeAPI
Resolve #278

[#278] 서버 통신 Response 값 GenericResponse로 리팩토링

---

Journey/Journey/Sources/AppModels/AppDate.swift
Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
Journey/Journey/Sources/Views/DatePickerViewController.swift
Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.swift

- AppDate 함수 day도 사용 가능하도록 수정 (피커에서는 day가 필요 없는데 글 작성할 때는 필요해서)
- 그에 따라서 기존 형식들 바뀌어서 day 없이 AppDate init 하던 것들 다 수정
- 기타 date 관련 코드들 약간씩 수정
Resolve #284
+) 
Locale을 ko-KR 로 하면 AppWeekday Enum이 굳이 필요없어서 지우고 AppDate의 Locale을 current가 아니라 한국 시간에 맞추도록 바꿨는데 약간 찝찝한데 그냥 쓸ㄲㅏ.. 해외에서 쓸 수도 있으니까...? 🙄🙄🙄🙄🙄🙄

[#284] AppDate 수정

---

Journey/Journey/Sources/APIModels/Home.swift
Journey/Journey/Sources/APIServices/HomeAPI/HomeAPI.swift

- HomeAPI - 서버 통신 Response 값 GenericResponse로 리팩토링
Resolve #280

[#280] HomeAPI - 서버 통신 Response 값 GenericResponse로 리팩토링

---

Journey/Journey/Resources/Constants/Xib.swift

코드리뷰 반영 커밋하다가 실수로 안올렸어요., 지송합니다

[#298] HeaderView Const 추가

---

Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
Journey/Journey/Sources/ViewControllers/Auth/CodeViewController.swift

- UI 변경사항 반영
- 에러처리
키보드에 따른 버튼 위치 이슈는 나중에 따로 이슈 파서 작업하겠습니다 ~
Resolve #304
https://user-images.githubusercontent.com/28949235/132119119-f6920f71-a7df-4513-b973-61796fddd783.mov

[#304] 인증번호 입력 뷰 변경사항 적용

---

Journey/Journey/Resources/Colors.xcassets/YellowText1.colorset/Contents.json
Journey/Journey/Resources/Colors.xcassets/todayYellow.colorset/Contents.json
Journey/Journey/Resources/Storyboards/Feed/MyDrawer.storyboard
Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.xib
Journey/Journey/Sources/Extensions/ModalPresentationController.swift
Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Journey/Journey/Sources/Views/DatePickerViewController.swift
Journey/Journey/Sources/Views/DatePickerViewController.xib
Journey/Journey/Sources/Views/FeedHeaderView.swift
Journey/Journey/Sources/Views/FeedHeaderView.xib
Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib

- custom pickerView 레이아웃 수정
- modal viewController background 수정 (blurEffect 제거)
- 컬렉션뷰 셀 교체, 레이아웃 수정
- 첫번째 셀 분기 처리
Resolve #310
https://user-images.githubusercontent.com/69361613/132119465-990942f6-fc84-4e67-b6fd-ed57f419f9ee.mp4

[#310] 내 서랍장 리디자인

---

Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
Journey/Journey/Sources/ViewControllers/Auth/FindPasswordViewController.swift

- UI 변경사항 적용
- 에러처리
아직 error message가 fix나지 않아서,, 픽스나면 새 이슈 파고 고치겠습니다!
Resolve #301

[#301] 비밀번호 찾기 뷰 변경사항 적용

---

Mohaeng/Mohaeng/Sources/Extensions/UINavigationItem+Extensions.swift

[#303] home navigation item 클릭 시 터지는 문제 해결

---

Mohaeng/Mohaeng/Resources/Storyboards/Challenge/CourseLibrary.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Mohaeng/Mohaeng/Sources/ViewModels/CourseListViewModel.swift

- 코스 라이브러리 코스 별로 filter 걸기
- 뷰 모델 수정, 그에 따라 VC도 수정
- 더미데이터 추가
- category, property가 혼용되고 있어서 property로 통일
Resolve #337

[#337] 코스 라이브러리 뷰 코스 별 filter

---

Mohaeng/Mohaeng/Sources/Extensions/UIView+Extension.swift

CGFloat -> Float으로 바꿨습니다.
CGLayer의 shadowOpacity는 Float형이라네요 .. 죗옹
Resolve #351

[#351] addShadowWithOpaqueBackground() 자료형 이슈

---

Mohaeng/Mohaeng.xcodeproj/xcshareddata/xcschemes/Mohaeng.xcscheme
Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift

- 오토레이아웃 수정
- 폰트 수정
Resolve #388

[#388] 로그인 뷰 오토레이아웃, 폰트 수정

---

Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/HomeHappy/HappyPopUpViewController.swift

- 자료형 잘못해서 0으로 나오고 있었어가지구 고쳤습니다
Resolve #447

[#447] 해피지수 프로그래스바에 반영

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Mohaeng/Mohaeng/Resources/Storyboards/Auth/FindPassword.storyboard
Mohaeng/Mohaeng/Resources/Storyboards/Auth/NewPassword.storyboard
Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/PasswordService.swift
Mohaeng/Mohaeng/Sources/SceneDelegate.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/FindPasswordViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift

패스워드 변경 뷰 수정
패스워드 변경
Resolve #441

[#441] 패스워드 변경 뷰, 통신

---

Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/LoginService.swift
Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift

[#497] 이메일로 로그인 / 회원가입 서버 수정

---

Mohaeng/Mohaeng/Resources/Constants/Storyboard.swift
Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
Mohaeng/Mohaeng/Resources/Storyboards/Auth/Agree.storyboard
Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/AgreeViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift

https://user-images.githubusercontent.com/80672561/140310143-32aa4bf2-fbae-4ad2-a5fc-023b6f7502c9.mp4
- 약관동의 웹페이지 연결
- 유리한테 컨펌 완료
Resolve #501

[#501] 약관동의 웹페이지 연결

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj

[#501] Agree 파일 추가

---

Mohaeng/Mohaeng/Resources/Storyboards/Home/MyPage.storyboard

마이페이지 캘린더 터치되는 현상 수정했습니다
Resolve #512

[#512] 마이페이지 캘린더 터치되는 현상 수정

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Mohaeng/Mohaeng/Resources/Storyboards/Home/Home.storyboard
Mohaeng/Mohaeng/Sources/AppModels/HomeMent.swift
Mohaeng/Mohaeng/Sources/AppModels/Ments.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.xib
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/HomeHappy/HappyPopUpViewController.swift

- 메인 멘트 수정
- 메인 프로그래스바 터치영역 수정
- 캐릭터뷰 인덱스 에러 수정
- 내 서랍장 Pop할때 없어지는 현상 수정
- 피드 헤더뷰 멘트 분기처리
- 로티 짤림 해결 #504 
Resolve #516

[#516] 2차 QA 반영

---

Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift

[#520] userDefault 없어서 에러나는 현상 해결

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

- 약관동의 폰트 수정
- SignUpSecond, SignUpThird 네비게이션 백버튼 추가
Resolve #517

[#517] 약관동의 폰트 수정 & 네비게이션바 백버튼 추가

---

Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

- SignUpThird에서 닉네임 저장
Resolve #537

[#537] 닉네임 UserDefaults

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift

[#528] 3차 QA 수정 사항

---

Mohaeng/Mohaeng/Sources/ViewControllers/Reward/ChallengeRewardViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Reward/CourseRewardViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Reward/LevelUpRewardViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Reward/WritingRewardViewController.swift

[#538] Reward flow 에 isPanalty 반영

---

Mohaeng/Mohaeng/Sources/Cells/CourseLibraryCollectionVIew/CourseLibraryCollectionViewCell.xib
Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib

3차 QA 수정사항
#531 반영 완료했습니다
Resolve #531

[#531]  3차 QA 반영

---

Mohaeng/Mohaeng/Sources/APIModels/CourseHistory.swift
Mohaeng/Mohaeng/Sources/APIServices/ChallengeAPI/ChallengeService.swift

완료한 코스 조회 response
챌린지뷰 header- client 추가
Resolve #544

[#544] 서버 변경사항 적용

---

Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift

[#550] 메인 멘트 로드 시점 변경

---

Mohaeng/Mohaeng/Resources/Storyboards/Challenge/Course.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/SettingViewController.swift

- 1대1 문의하기 연결했습니다.
- MFMailComposeViewControllerDelegate 사용하지 않고 mailTo를 사용했습니다
https://user-images.githubusercontent.com/28949235/140893659-8f85d446-ae13-4ccf-a732-888d286e80c4.mov
Resolve #542

[#542] mailTo 함수 추가

---

Mohaeng/Mohaeng/Resources/Storyboards/Tabbar.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/TabbarViewController.swift

탭바 스크롤 시 배경 사라지는 이슈 해결했습니다.
Resolve #541

[#541] Tabbar background iOS15 대응

---

Mohaeng/Mohaeng/Sources/Extensions/UINavigationController+Extension.swift
Mohaeng/Mohaeng/Sources/ViewControllers/OnBoarding/OnBoarding1ViewController.swift

기존 NavigationController Extension 삭제
온보딩1VC에 적용 안 되어있어서 변경했습니다
Resolve #367

[#367] 기존 NavigationController Extension 삭제

---

Mohaeng/Mohaeng/Sources/Cells/CourseLibraryCollectionVIew/CourseCategoryCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift

iOS 14 이하에서 코스 라이브러리 property collectionView 중복 선택되는 이슈 해결
Resolve #556

[#556] iOS 14 이하에서 코스 라이브러리 property collectionView 중복 선택되는 이슈 해결

---

Mohaeng/Mohaeng/Resources/Storyboards/Home/Home.storyboard

- 메인뷰 로티 레이아웃 수정했습니다 
Resolve #560

[#550] 메인뷰 로티 레이아웃 수정

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.xib
Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift

iPhone 8, 14.4
iPhone 12 Pro, 15.0
Resolve #557

[#557] 채팅 뷰 cell truncation, height 이슈 해결

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard

- 개인정보 수집 버튼 사라지는 이슈 해결
Resolve #563

[#563] 약관 동의 수정

---

Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift

- 괄호를 잘못 닫았습니다 ..
Resolve #564

[#564] SignUpApi 머지 이슈

---

Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift

[#558] WritingVC header client 추가

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift

진짜 1분만에 답장했는데 아직도 답 안해즈서 그냥 내 맘대로 바꿧음
Resolve #568

[#568] 피드 멘트 변경

---

Mohaeng/Mohaeng/Resources/Storyboards/Home/CourseHistory.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/CourseHistoryViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift

챌린지 기록보기 empty 뷰 추가
Resolve #572

[#572] 챌린지 기록보기 empty 뷰 추가

---

Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/MyPageViewController.swift

불필요한 reload 삭제
select가 두번되는 현상 해결
Resolve #573

[#573] pop했을 때 calendar 색 사라지는 이슈 해결

---

Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift

- 로그인 버튼 살리기
- 코드 리팩토링은 .. 여융 ㅣㅆ을 때 조질게요..
Resolve #570

[#570] 로그인 버튼 살리기

---

README.md

[#NON_ISSUE] README 사진 변경

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift

[#579] 오타 수정

---

Mohaeng/Mohaeng/Sources/ViewControllers/Auth/FindPasswordViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift

[#583] 비밀번호찾기 특수문자 포함 검사 추가

---

Mohaeng/Mohaeng/Sources/ViewControllers/Reward/CourseRewardViewController.swift

[#588] Reward 이슈 수정

---

Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

[#590] 기기 대응 및 스티커 레이아웃 수정

---

Mohaeng/Mohaeng/Sources/AppModels/Reward.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

[#592] Reward, Feed 버그 수정

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/NewPassword.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift

- SignUpFirst
- NewPassword
Resolve #593

[#593] 비밀번호 8,12 로 수정

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj

[#595]  아이패드 타겟 제거

---

Mohaeng/Mohaeng/Resources/Storyboards/Challenge/Course.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/OnBoarding/OnBoarding3ViewController.swift
Mohaeng/Mohaeng/Sources/Views/CourseHeaderView.swift
Mohaeng/Mohaeng/Sources/Views/CourseHeaderView.xib

리젝사항 수정 외, 변경사항 및 버그 반영했습니다
resolve #598

[#598] 챌린지뷰 네비바 고정, section header 날짜 연결

---

Mohaeng/Mohaeng/Sources/AppDelegate.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

가로모드를 제한했고,
셀 안에서 root 뷰컨을 불러와서 present하는 방식이 종종 안되는 듯해서 Delegate로 바꿨습니닷
Resolve #601, #600

[#600, #601] 가로모드 제한 및 팝업 present 방식 변경

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

[#601] delete post Id

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

- 신고 버튼 클릭 시 경고 알럿을 띄웁니다.
Resolve #601

#601: 신고 버튼 선택 시 경고 alert

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/AgreeViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift

[#606] EULA

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

[#608] bug fix

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift

https://user-images.githubusercontent.com/80672561/142959067-f798dd00-2622-4e14-bb07-9a42ad17de32.mov
- 약관 동의 UI 수정
Resolve #610

[#610] 약관 동의 UI 수정

---

Mohaeng/Mohaeng/Resources/Constants/URL.swift
Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedAPI.swift
Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift

사용자 블락 기능 추가했습니다.
Resolve #612

[#612] 사용자 블락 로직 추가

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Mohaeng/Mohaeng/Resources/Storyboards/Feed/Feed.storyboard
Mohaeng/Mohaeng/Resources/Storyboards/Feed/FeedDetail.storyboard
Mohaeng/Mohaeng/Sources/APIModels/Feed.swift
Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedAPI.swift
Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/PlusButtonCollectionViewCell.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift

- 피드 메인뷰 페이징
- 피드 둘러보기뷰 아래위 페이징
멍가 둘러보기뷰에서 약간 어색한 느낌인데 테플 올라가면 기기로 테스트해볽게요
https://user-images.githubusercontent.com/69361613/144053156-5f5f8255-024b-458c-b37b-89e7eb42a52f.mp4
https://user-images.githubusercontent.com/69361613/144053310-344bdb39-5a49-4b5a-b6c5-79e03cbc7aa4.mp4
Resolve #614

[#614] 커뮤니티 페이징

---

Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/EmailLoginViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/SettingViewController.swift

- 로그아웃, 회원탈퇴 시 푸쉬알림 unregister
- 재로그인, 회원가입 시 푸쉬알림 register
Resolve #617

[#617] 로그아웃, 회원탈퇴 시 푸쉬알림은 계속 오는 현상 수정

---

Mohaeng/Mohaeng/Resources/Storyboards/Auth/EmailLogin.storyboard

- 밑줄 뷰 높이 0.5로 바꿨습니다.
- width를 위의 라벨이랑 맞췄습니다.
Resolve #625

[#625] 이메일로 로그인 밑줄 수정

---

Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Mohaeng/Mohaeng/Sources/ViewControllers/Feed/WritingViewController.swift

- #626 
리디자인은 이번주 주말 혹은 다음주 주말,,, 안으로~! 해볼게요오~~

[#626] 글쓰기뷰 글자수 제한 수정, 피드 뷰 로티 hidden 값 수정

---

Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift

[#629] 닉네임 저장
